version: '3'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb:/data/db
  api:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      MONGO_URI: mongodb://db/films
volumes:
  mongodb:
