version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
  api:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    environment:
      MONGO_URI: 'mongodb://db:27017/films'
      PORT: 3000

volumes:
  mongodb:
